/**
 * init command — Initialize kbase in the current project.
 *
 * Creates .knowledge/ and its internal subdirectories, drops a
 * placeholder index.md, wires _cache/ into .gitignore, and prints
 * the agent-side setup instructions. Idempotent: running it twice
 * on the same directory is safe and will only fill in missing pieces.
 */

import type { Command } from "commander";
import fs from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

const KBASE_HOOK_READ = "kb hook-read";
const KBASE_HOOK_WRITE = "kb hook-write";

/**
 * Placeholder body for a fresh index.md. `kb reindex` and `write_knowledge`
 * both overwrite this on first real activity. We write something rather
 * than leaving the file empty so MCP clients calling `read_knowledge`
 * before the first write don't trip on a zero-byte file.
 */
const INDEX_PLACEHOLDER = `# Knowledge Base Index

> No entries yet. This file is regenerated by \`kb reindex\` and by
> every \`write_knowledge\` MCP call. It will populate automatically
> as entries are added.
`;

/**
 * MCP + agent wiring instructions. Printed at the end of `kb init` so
 * users see the next step without needing to read the README.
 */
const POST_INIT_MESSAGE = `
  kbase initialized.

  Next steps:

  1. Wire the MCP server into your agent.

       Claude Code:
         claude mcp add kbase -- kb-mcp

       Cursor (.cursor/mcp.json):
         {
           "mcpServers": {
             "kbase": { "command": "kb-mcp" }
           }
         }

  2. Tell your agent to use it. Add to CLAUDE.md / .cursorrules:

       This project uses kbase. Before making changes, call
       read_knowledge for the relevant module or file. After making
       non-trivial changes, call write_knowledge to record what you
       decided and why. Before large refactors, call query_deps to
       check the blast radius.

  3. On the first write_knowledge call, the _graph/ indexes and
     index.md will be generated automatically. You can also run
     \`kb reindex\` at any time to rebuild them from the markdown.
`;

/**
 * Ensure a directory exists. Returns true if it was created, false if
 * it already existed. mkdir with recursive is idempotent, so we stat
 * first only to decide which message to print.
 */
async function ensureDir(dir: string): Promise<boolean> {
  try {
    const stat = await fs.stat(dir);
    if (stat.isDirectory()) return false;
  } catch {
    // not present — fall through to create
  }
  await fs.mkdir(dir, { recursive: true });
  return true;
}

/**
 * Append a pattern to .gitignore if it isn't already listed. We do a
 * line-by-line scan rather than a substring check so we don't get
 * confused by a comment that mentions the pattern.
 */
async function addToGitignore(cwd: string, pattern: string): Promise<boolean> {
  const gitignorePath = path.join(cwd, ".gitignore");
  let existing = "";
  try {
    existing = await fs.readFile(gitignorePath, "utf-8");
  } catch (err: unknown) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
  }

  const alreadyListed = existing
    .split("\n")
    .some((line) => line.trim() === pattern);
  if (alreadyListed) return false;

  const separator = existing.length > 0 && !existing.endsWith("\n") ? "\n" : "";
  await fs.writeFile(
    gitignorePath,
    existing + separator + pattern + "\n",
    "utf-8"
  );
  return true;
}

/**
 * Additively merge kbase hook entries into .claude/settings.json.
 * Returns true if hooks were added, false if already present.
 */
export async function mergeHooksIntoSettings(settingsPath: string): Promise<boolean> {
  const raw = await fs.readFile(settingsPath, "utf-8");
  const settings = JSON.parse(raw);

  if (!settings.hooks) settings.hooks = {};
  if (!settings.hooks.UserPromptSubmit) settings.hooks.UserPromptSubmit = [];
  if (!settings.hooks.Stop) settings.hooks.Stop = [];

  const hasReadHook = settings.hooks.UserPromptSubmit.some(
    (h: any) => h.hooks?.some((inner: any) => inner.command?.includes(KBASE_HOOK_READ)),
  );
  const hasWriteHook = settings.hooks.Stop.some(
    (h: any) => h.hooks?.some((inner: any) => inner.command?.includes(KBASE_HOOK_WRITE)),
  );

  if (hasReadHook && hasWriteHook) return false;

  if (!hasReadHook) {
    settings.hooks.UserPromptSubmit.push({
      hooks: [{ type: "command", command: KBASE_HOOK_READ }],
    });
  }

  if (!hasWriteHook) {
    settings.hooks.Stop.push({
      hooks: [{ type: "command", command: KBASE_HOOK_WRITE }],
    });
  }

  await fs.writeFile(settingsPath, JSON.stringify(settings, null, 2) + "\n");
  return true;
}

/**
 * Register the `kb init` subcommand.
 */
export function register(program: Command): void {
  program
    .command("init")
    .description("Initialize kbase in the current directory")
    .option("--no-hooks", "Skip Claude Code hook installation")
    .action(async (_opts: Record<string, unknown>) => {
      const cwd = process.cwd();
      const knowledgeDir = path.join(cwd, ".knowledge");

      // Create the three directories. Order is deliberate: parent first,
      // then the two internal dirs. All three go through ensureDir so a
      // re-run that finds some already present still fills in the rest.
      const createdRoot = await ensureDir(knowledgeDir);
      console.log(
        createdRoot
          ? "  Created .knowledge/"
          : "  .knowledge/ already exists — skipping"
      );

      await ensureDir(path.join(knowledgeDir, "_graph"));
      await ensureDir(path.join(knowledgeDir, "_cache"));

      // Only write the placeholder index.md if nothing is there yet.
      // Overwriting would clobber a real index generated by a prior run
      // or checked in from another machine.
      const indexPath = path.join(knowledgeDir, "index.md");
      try {
        await fs.access(indexPath);
      } catch {
        await fs.writeFile(indexPath, INDEX_PLACEHOLDER, "utf-8");
        console.log("  Wrote placeholder .knowledge/index.md");
      }

      // _cache/ is per-developer and disposable; _graph/ is part of the
      // reproducible state and stays committed so fresh clones can
      // query_deps without running kb reindex first.
      const added = await addToGitignore(cwd, ".knowledge/_cache/");
      if (added) console.log("  Added .knowledge/_cache/ to .gitignore");

      // Hook wiring
      if (!_opts.noHooks) {
        const settingsPath = path.join(cwd, ".claude", "settings.json");
        if (existsSync(settingsPath)) {
          const wired = await mergeHooksIntoSettings(settingsPath);
          if (wired) {
            console.log("  Wired kbase hooks into .claude/settings.json");
          } else {
            console.log("  kbase hooks already present in .claude/settings.json");
          }
        } else {
          console.log("\n  No .claude/settings.json found.");
          console.log("  To enable kbase hooks, add to your .claude/settings.json:\n");
          console.log(JSON.stringify({
            hooks: {
              UserPromptSubmit: [{ hooks: [{ type: "command", command: KBASE_HOOK_READ }] }],
              Stop: [{ hooks: [{ type: "command", command: KBASE_HOOK_WRITE }] }],
            },
          }, null, 2));
        }
      }

      console.log(POST_INIT_MESSAGE);
    });
}
